version: '3.8'
services:
  web:
    build: ./
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static:/code/static
    env_file:
      - movies_admin/.env
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - movies_admin/.env

  nginx:
    image: nginx:1.20
    depends_on:
      - web
    restart: always
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/site.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/site/static
    ports:
      - "80:80"
#
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      volumes:
        - .els:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"

  etl:
      build: postgres_to_es/
      deploy:
        restart_policy:
          condition: any
          delay: 5s
          window: 5s
      depends_on:
        - db
        - elasticsearch
      env_file:
        - .env
      volumes:
        - ./postgres_to_es/volumes/:/sites/states/

volumes:
  postgres_data:
  static: