version: '3.8'
services:
  web:
    build: ./
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static:/code/static
    env_file:
      - ./.env.default
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.default

  nginx:
    image: nginx:1.20
    depends_on:
      - web
    restart: always
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/site.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/site/static
    ports:
      - "80:80"


volumes:
  postgres_data:
  static: